### ISSUE TITLE
Transpile package code

### ISSUE THREAD

**Issue by Lenn-xsr** [Lenn-xsr/db-local#16]
I have another problem when creating an executable with PKG
I get the following error when compiling
`
F:\ProyectoKong\BrowserBear\node_modules\db-local\lib\utils.js
  Dynamic require may fail at run time, because the requested file
  is unknown at compilation time and not included into executable.
  Use a string literal as an argument for 'require', or leave it
  as is and specify the resolved file name in 'scripts' option.
> Warning Cannot include directory %1 into executable.
> Warning Failed to make bytecode node10-x86 for file C:\snapshot\BrowserBear\node_modules\db-local\lib\utils.js
> Warning Failed to make bytecode node10-x86 for file C:\snapshot\BrowserBear\node_modules\db-local\lib\modules\methods.js
> Warning Failed to make bytecode node10-x86 for file C:\snapshot\BrowserBear\node_modules\db-local\lib\modules\schema.js
`
and when I run the application with CMD window it shows me this error

`
C:\snapshot\BrowserBear\node_modules\db-local\lib\modules\schema.js:27
    (schema?._id?.type === Number && !schema?._id?.default)
            ^

SyntaxError: Unexpected token .
    at Module._compile (internal/modules/cjs/loader.js:721:23)
    at Module._compile (pkg/prelude/bootstrap.js:1758:32)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:651:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:591:12)
    at Function.Module._load (internal/modules/cjs/loader.js:583:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at Module.require (pkg/prelude/bootstrap.js:1676:31)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\snapshot\BrowserBear\node_modules\db-local\lib\index.js:1:78)
`

_Originally posted by @CarmenLexa in https://github.com/Lenn-xsr/db-local/issues/15#issuecomment-1101511340_

**Comment by CarmenLexa** [comment]
the error persists I have already upgraded node to the latest version
`
C:\snapshot\BrowserBear\node_modules\db-local\lib\modules\schema.js:27
    (schema?._id?.type === Number && !schema?._id?.default)
            ^

SyntaxError: Unexpected token .
    at Module._compile (internal/modules/cjs/loader.js:721:23)
    at Module._compile (pkg/prelude/bootstrap.js:1758:32)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:651:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:591:12)
    at Function.Module._load (internal/modules/cjs/loader.js:583:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at Module.require (pkg/prelude/bootstrap.js:1676:31)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\snapshot\BrowserBear\node_modules\db-local\lib\index.js:1:78)
`

**Comment by Lenn-xsr** [comment]
Can you send me the return of the command "npm -v" in your console?

The code itself is correct, it just needs a node version above or equal to 14v

**Comment by Lenn-xsr** [comment]
> the error persists I have already upgraded node to the latest version ` C:\snapshot\BrowserBear\node_modules\db-local\lib\modules\schema.js:27 (schema?._id?.type === Number && !schema?._id?.default) ^
> 
> SyntaxError: Unexpected token . at Module._compile (internal/modules/cjs/loader.js:721:23) at Module._compile (pkg/prelude/bootstrap.js:1758:32) at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10) at Module.load (internal/modules/cjs/loader.js:651:32) at tryModuleLoad (internal/modules/cjs/loader.js:591:12) at Function.Module._load (internal/modules/cjs/loader.js:583:3) at Module.require (internal/modules/cjs/loader.js:690:17) at Module.require (pkg/prelude/bootstrap.js:1676:31) at require (internal/modules/cjs/helpers.js:25:18) at Object. (C:\snapshot\BrowserBear\node_modules\db-local\lib\index.js:1:78) `

Can you send me the return of the command "npm -v" in your console?

The code itself is correct, it just needs a node version above or equal to 14v
